

CREATE TABLE AndroidClients(
   ID INTEGER PRIMARY KEY   AUTOINCREMENT,
   USERNAME       CHAR(50)   NOT NULL,
   PASSWORD       CHAR(50)   NOT NULL,
   DEVICEID       CHAR(50)
);

CREATE TABLE RaspberryPi(
   ID INTEGER PRIMARY KEY  AUTOINCREMENT,
   SERIALNO       CHAR(50)	NOT NULL UNIQUE

);


CREATE TABLE users(
   USERID INT  NOT NULL UNIQUE,
   PIID	  INT  NOT NULL,
   FOREIGN KEY (USERID) REFERENCES AndroidClients(ID),
   FOREIGN KEY (PIID) REFERENCES RaspberryPi(ID),
   UNIQUE(USERID, PIID)
   
);

CREATE TABLE OneTimeUser(
   ID INTEGER PRIMARY KEY   AUTOINCREMENT,
   USERNAME       CHAR(50)   NOT NULL ,
   PASSWORD       CHAR(50)   NOT NULL,
   FLAG 		BOOLEAN NOT NULL,
   SERIALNO       CHAR(50)	NOT NULL,
   ADDEDBY 		 CHAR(50)   NOT NULL
);


CREATE TABLE OneTimeUserLog(
   ID INTEGER PRIMARY KEY ,
   LOCKSTATUS       CHAR(50)   NOT NULL,
   TIMESTAMP       DATETIME   NOT NULL
   
);




INSERT INTO AndroidClients (USERNAME,PASSWORD,DEVICEID) VALUES ('acngroup10', 'doorlock');

INSERT INTO AndroidClients (USERNAME,PASSWORD,DEVICEID) VALUES ('admin', 'doorlock');

INSERT INTO AndroidClients (USERNAME,PASSWORD,DEVICEID) VALUES ('acn', 'doorlock');



INSERT INTO RaspberryPi (SERIALNO) VALUES ('bcddadas12300000435dffs');
INSERT INTO RaspberryPi (SERIALNO) VALUES ('bcddadas12400000436dffs');
INSERT INTO RaspberryPi (SERIALNO) VALUES ('bcddadas12500000437dffs');


INSERT INTO users (USERID,PIID) VALUES (1, 1);

INSERT INTO users (USERID,PIID) VALUES (2, 2);

INSERT INTO OneTimeUserLog (ID,LOCKSTATUS,TIMESTAMP) VALUES (1, 'locked','2014-05-09 20:17:40');
INSERT INTO OneTimeUserLog (ID,LOCKSTATUS,TIMESTAMP) VALUES (2, 'locked','2014-05-09 20:17:40');
INSERT INTO OneTimeUserLog (ID,LOCKSTATUS,TIMESTAMP) VALUES (3, 'locked','2014-05-09 20:17:40');
INSERT INTO OneTimeUserLog (ID,LOCKSTATUS,TIMESTAMP) VALUES (4, 'locked','2014-05-09 20:17:40');
INSERT INTO OneTimeUserLog (ID,LOCKSTATUS,TIMESTAMP) VALUES (5, 'unlocked','2014-05-09 20:17:40');
INSERT INTO OneTimeUserLog (ID,LOCKSTATUS,TIMESTAMP) VALUES (6, 'locked','2014-05-09 20:17:40');
INSERT INTO OneTimeUserLog (ID,LOCKSTATUS,TIMESTAMP) VALUES (7, 'unlocked','2014-05-09 20:17:40');
INSERT INTO OneTimeUserLog (ID,LOCKSTATUS,TIMESTAMP) VALUES (8, 'locked','2014-05-09 20:17:40');
INSERT INTO OneTimeUserLog (ID,LOCKSTATUS,TIMESTAMP) VALUES (9, 'unlocked','2014-05-09 20:17:40');








